version: "3.9"

services:
  tests:
    build: .
    environment:
      BASE_URL: https://demo.sylius.com
      WORKERS: "2"
    shm_size: 1gb
    working_dir: /tests
    volumes:
      - ./playwright-report:/tests/playwright-report   # отчёт на хост
      - ./:/tests                                      # код с хоста
      - node_cache:/tests/node_modules                 # именованный том для node_modules
    command: >
      bash -lc '
        if [ ! -d node_modules ] || [ -z "$(ls -A node_modules)" ]; then
          npm ci;
        fi;
        npx playwright test --reporter=html
      '

volumes:
  node_cache:

