services:
  tests:
    build: .
    image: sylius-pw-runner:1.54
    shm_size: 1gb
    working_dir: /app/src
    environment:
      - BASE_URL=https://demo.sylius.com/en_US/
      - WORKERS=2
      - PLAYWRIGHT_HTML_REPORT=/app/src/playwright-report
    volumes:
      - .:/app/src
    command: ["/bin/bash", "/app/src/scripts/run.sh"]

