name: Playwright Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.54.2-jammy
    env:
      BASE_URL: https://demo.sylius.com

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx playwright test --reporter=html
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
